apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers
  namespace: tasleem-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers
  namespace: tasleem
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: developer
