webex_room: ENC[AES256_GCM,data:c3CKDXwoCgJn/7Mvw3olPTM44ESPXk6L1kVV1NOm9avAGsfllCWonA4G6+kP3RoIDztEB+jPhl6AglXc1vmxu2RDkev8ZhElvEL8c4oGKOES1pgxG0BcAkMwz7oUkqI9GR19Iw==,iv:sCHFWrdQCMozQvdAMbNLJPmCjgv9DhZGe3u5CEbJ7aM=,tag:KZ02NUVZhgv96CpOVDBrhA==,type:str]
webex_token: ENC[AES256_GCM,data:Uu0fL6a8BcRtgtp2NVOvoAGx6a89ayiUJzMpalPfcmCVJiemkaVnPXEGCBT+MdXvTI3Lh1SNPp9Hi5iA3y7kHcc2Ch3wnE14HD9Ve7GYYsJPFud/e1ZOZ1VORoTH3wFiylSftlIz9ryyYw==,iv:10eMHgIjxMiLXW1SJqVE1+FT0rUus1oybWyyQEd+n2Y=,tag:PVR6f/xz+hTGwI76ypRLqA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:310830963532:key/mrk-9e8c23191f1741289211dadb4d0767e8
          created_at: "2022-03-15T11:03:55Z"
          enc: AQICAHg/l3PW9DQsmOmkmKzHr1yZLJ4ZNJ0/QSakfJT5vDDv+wGcg7W5BJcipkVB8KpwL6QeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSHiwpryMGynyHm/qAgEQgDvyVjFOgxmuwLjHki1Js1UqYT6h1Ds2K6vX3vqs5Y5qLeaDVd0U2PRDUrVFz6WDICDsTCKJQH+DNQb9fQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-15T11:03:56Z"
    mac: ENC[AES256_GCM,data:gsU7Y/0iWeiCPAI1U0CDHh8LKTFRw1t6EVvRUX1R+aJyVFYfXNH59eIGMrIWYW1buSQ5eQ1NQigXyt81xVuLXxF4tuN3t+GvoniA4a6WnxuzyvHyc4vhFsr6cMsLjX4yBNbpQ8X8olJWdZ+zyqwAOqq92HgpBQHpJvLNwgGVUNg=,iv:1pJyZM8rHCxwCOy+JhxylbshmPa/sVBBJh7CTCqYiLM=,tag:1xjMxwoQr0frmTCIsSPk1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
