access_key: ENC[AES256_GCM,data:DzOGbXeZg7FWfaSvXXnDIMYbwvrsl2QT6C0MOCtYfUmxr/M=,iv:uTJZw5mvycRPOz81v6JxxpaMfsFDDOqVw3ZJLFNUdeE=,tag:LGCi6Dwg0YeBg374+0HWBw==,type:str]
secret_key: ENC[AES256_GCM,data:1X8Q1KxZ28zvqwU7lhwCWoCNoPYu6w==,iv:7z6gtPYh0ReLon1vysiijCenFK+JJGNpeN1o/1CmObI=,tag:jvxgoofx1YZivn2Spw31tg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:310830963532:key/mrk-9e8c23191f1741289211dadb4d0767e8
          created_at: "2023-01-14T14:13:43Z"
          enc: AQICAHg/l3PW9DQsmOmkmKzHr1yZLJ4ZNJ0/QSakfJT5vDDv+wHQoFhGvsAHICWApd+PZZEfAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbCQbEhxqe3clEmpUAgEQgDsOlun0ErCSRfLsvmxq7ypT340+31YoTL/Ad9KVJDIt3ThnKtjTkJdMowEYpnrhyOJzicM+7BGIZyfJSw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-31T12:48:22Z"
    mac: ENC[AES256_GCM,data:jZj9j7TiJaQTeljh/IrxaY9E30IkTC6SNv3wIJwCh41a92+0w6Hw/TqmDCVIIBrbV5P0gy2cSYaJlGDK13Doc+H3vlG5uW7Fck71K2F3hJHZR5A0R9M9PISttZk/WUaSUEhDiCKPkBpsTDEmPUt/3txVRCcTa38SblX6NdL7Qwk=,iv:N4DqN3W4O+cPvGnNDm2p1mdony2YlwsW4WjviNOum6k=,tag:mRJDfygBYs5DTUqUh963gg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
