apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-tasleem-production
spec:
  consolidation:
    enabled: true
  weight: 10
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: NotIn
      values:
        - m6g.16xlarge
        - m6gd.16xlarge
        - r6g.16xlarge
        - r6gd.16xlarge
        - c6g.16xlarge
        - t3.nano
        - t3.micro
        - t3.small
        - t3.medium
        - c5d.large
        - t3a.nano
        - t3a.micro
        - t3a.small
        - t3a.medium
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
    - key: "kubernetes.io/arch"
      operator: In
      values:
        - amd64
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        - spot
        - on-demand
  limits:
    resources:
      cpu: "64"
      memory: 256Gi
  providerRef:
    name: eks-tasleem-production
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: eks-tasleem-production
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    karpenter.sh/discovery: eks-tasleem-prod
  securityGroupSelector:
    karpenter.sh/discovery: eks-tasleem-prod
  tags:
    Environment: production
    Owner: Creative DevOps
    Project: TASLEEM
