apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-tamata-staging
spec:
  consolidation:
    enabled: true
  # ttlSecondsAfterEmpty: 300
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
      - c5a.xlarge
      - c5.xlarge
      - c5ad.xlarge
      - c6a.xlarge
      - c5a.2xlarge
      - c5.2xlarge
      - c5ad.2xlarge
      - c6a.2xlarge
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
      - eu-central-1a
      - eu-central-1b
    - key: "kubernetes.io/arch"
      operator: In
      values:
      - amd64
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
      - spot
  limits:
    resources:
      cpu: "64"
      memory: 256Gi
  providerRef:
    name: tamata-staging-app
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-tamata-staging-main
spec:
  ttlSecondsAfterEmpty: 300
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
        - t3a.xlarge
        - t3.xlarge
        - t3a.2xlarge
        - t3.2xlarge
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
      - eu-central-1a
      - eu-central-1b
    - key: "kubernetes.io/arch"
      operator: In
      values:
      - amd64
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
      - spot
  taints:
    - effect: NoSchedule
      key: "group"
      value: "main"
  labels:
    group: "main"
  limits:
    resources:
      cpu: "16"
      memory: 64Gi
  providerRef:
    name: tamata-staging-main
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-tamata-staging-gpu
spec:
  consolidation:
    enabled: true
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
        - g4dn.xlarge
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - eu-central-1a
        - eu-central-1b
    - key: "kubernetes.io/arch"
      operator: In
      values:
        - amd64
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        - spot
        - on-demand
  taints:
    - key: nvidia.com/gpu
      effect: "NoSchedule"
  labels:
    group: "gpu"
  providerRef:
    name: tamata-staging-app-gpu
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: tamata-staging-app
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    karpenter.sh/discovery: eks-tamata-staging
  securityGroupSelector:
    karpenter.sh/discovery: eks-tamata-staging
  tags:
    Environment: staging
    Owner: Creative DevOps
    Project: TAMATA
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        iops: 3000
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: tamata-staging-main
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    karpenter.sh/discovery: eks-tamata-staging
  securityGroupSelector:
    karpenter.sh/discovery: eks-tamata-staging
  tags:
    Environment: staging
    Owner: Creative DevOps
    Project: TAMATA
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: tamata-staging-app-gpu
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    karpenter.sh/discovery: eks-tamata-staging
  securityGroupSelector:
    karpenter.sh/discovery: eks-tamata-staging
  tags:
    Environment: staging
    Owner: Creative DevOps
    Project: TAMATA
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
