apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-tejan-prod
spec:
  ttlSecondsAfterEmpty: 300
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: NotIn
      values: ["t3a.small", "t3.small", "t3a.medium", "t3.medium" ]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: "256"
      memory: 512Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: eks-tejan-prod
    securityGroupSelector:
      karpenter.sh/discovery: eks-tejan-prod
