webex_room: ENC[AES256_GCM,data:9PT9/Vycw3mOAZPcg0Njoi9Ntr9MQsI8ghj8SYslLKAlnG7b0EpFcy7HGqeMZqj7oNPlUtf3bU3NdqeD12VFKzSVc5iCdGGcY23LEL7MvOltjuceo6+pGCwvS0clc5l8Ni58xA==,iv:C4kpjApgjiJgpyXVbGJ0rxLigpb5bYwt8mHW/YI9xvo=,tag:nuB1xk26H3gaRqIFwapY9Q==,type:str]
webex_token: ENC[AES256_GCM,data:GPLKTW/CPw6x5IY6MvMY21CImwd+Y1S18doewYGIg/Cqn1le8dEU7vdO/Y3F6wqcS9j+EYanYIFAq5dZ9rX6L4sd8LpdLmqwWaEwSxqgZPu560HLzqrKX9J8HIiieXxaUBOFKTZrYJL41w==,iv:kOfK4PIaBEESwl67gk2oxPoz6JmtRuJRWusyvZ03kEs=,tag:u/C7L/LVNn8sv5FIZadIaQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:310830963532:key/mrk-9e8c23191f1741289211dadb4d0767e8
          created_at: "2022-03-16T11:29:44Z"
          enc: AQICAHg/l3PW9DQsmOmkmKzHr1yZLJ4ZNJ0/QSakfJT5vDDv+wEmh3O9nyocLAA8LTBsfBm6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKdzi/2uI9r6t5vbKAgEQgDv426SNM5qbISi5mb7pC00cOm40Vglmj6kMcbX/1nbdAuU8PDNuhxI7konZur8lD2UwwiA4JFU5pPD52w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-16T11:29:45Z"
    mac: ENC[AES256_GCM,data:FHoYgMA1/Ab3D/NoUXj8oiO0bJ2xs8GEdUggYDpBIbiRNmaWcEQ0Jfyp2ckHr7IDq/T3Eq054PcJ/tH7SkftkRlOeiQtgEt7xbx5yorjYin8rYAZMFBYZpzpkz3FGvaoW0VNMAvhGbQjJnEslUetKVsbA3zhPBTi7MGsVyeYyQU=,iv:/J5x6QH09nvlzhYpczVFb0I4YoH0+D1k8fVBgQNanEc=,tag:SRmu1i2sM6RLhe4895BAGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
