apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-smb-staging
spec:
  consolidation:
    enabled: true
  requirements:
  - key: "node.kubernetes.io/instance-type"
    operator: In
    values:
    - m5.4xlarge
    - m5a.4xlarge
    - t3.2xlarge
  - key: "topology.kubernetes.io/zone"
    operator: In
    values:
    - eu-central-1a
    - eu-central-1b
  - key: "kubernetes.io/arch"
    operator: In
    values:
    - amd64
  - key: "karpenter.sh/capacity-type"
    operator: In
    values:
    - spot
  limits:
    resources:
      cpu: "64"
      memory: 256Gi
  providerRef:
    name: eks-smb-staging
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: eks-smb-staging
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    karpenter.sh/discovery: eks-smb-staging
  securityGroupSelector:
    karpenter.sh/discovery: eks-smb-staging
  tags:
    Environment: staging
    Owner: Creative DevOps
    Project: SMB
