---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: eks-creative-advtech-infra
spec:
  consolidation:
    enabled: true
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: NotIn
      values:
        - "t3a.small"
        - "t3.small"
        - "t3a.medium"
        - "t3.medium"
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "eu-central-1a"
        - "eu-central-1b"
    - key: "kubernetes.io/arch"
      operator: In
      values:
        - "amd64"
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        - "spot"
  limits:
    resources:
      cpu: "96"
      memory: 512Gi
  providerRef:
    name: eks-creative-advtech-infra
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: eks-creative-advtech-infra
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelector:
    karpenter.sh/discovery: eks-creative-advtech-infra
  securityGroupSelector:
    karpenter.sh/discovery: eks-creative-advtech-infra
  tags:
    Environment: production
    Owner: Creative DevOps
    Project: creative-advtech
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
