access_key: ENC[AES256_GCM,data:vxwMmqSjJafhYofADLgmQbOM/g0=,iv:h2eAuQODQNsZFXGngXU50mDhEjplljaNnEkQw4/jaSM=,tag:pUlEzaAM8dv1GGaJcGJVzQ==,type:str]
secret_key: ENC[AES256_GCM,data:FZGgJ1s3Vzvxm6FNelLsfXWzOCXuWr2FdSqR+qutb94RIlnopQx6qQ==,iv:bWHe7kQUXlEMmbI8T2RFS+M8RAxwCdgnBd3r+Io7rh8=,tag:6nG0Lp1Ai++pZ2Zj/0q7JQ==,type:str]
Recovery Key 1: ENC[AES256_GCM,data:ZKEhaOGYPNaQN0HTcp/3HuHC++iR7WNsBuLorWRXRHjxquk6QQy4uLRxEzQ=,iv:yubK19NMD/y/iIGx/rwbDOxBNIDXf73w6//Rh2dYH8g=,tag:MiONppTm4EEmoBcJgihVsw==,type:str]
Recovery Key 2: ENC[AES256_GCM,data:t9K9PdoPtG7P3morK9f6bBYYTD/932ZQKeWYFQBoqIxnRv+hVCR7IIc1vt4=,iv:s1Tvme6PbwWhgmp5lrEVo7LISeAxodZC6VTWs6ffx3Y=,tag:jyfW+or3fd4zWaTJIMj2EQ==,type:str]
Recovery Key 3: ENC[AES256_GCM,data:WI02T0jFZ1WbtXU7/ukQ3y/sH5AzYXwxXlgJRhNJrkMC9QlUFehEeopvTqc=,iv:0CToJP+IndWzErocmFoH6p4sG6ebwYS2kr2L+Wuj2Ek=,tag:LK8bLWuX0R00flGVPZnhOw==,type:str]
Recovery Key 4: ENC[AES256_GCM,data:Y0DnpWRNpFnSvD4c9ZTzm8HDg/hIlVCmJJ5CMHsZChw0X+8kD8/SLbcCH40=,iv:nyAXgT/HmhFDJO1/6zMEo8PoMLIrC41bJ1Ysuep8/NI=,tag:/n9xM00qOFoVG8MW0T8Vag==,type:str]
Recovery Key 5: ENC[AES256_GCM,data:O8Bcm/i7pzKrnEd5uoJXl4CawqqcaQ/kXk69eyv3pAs2oMf0kBl4XMy6qMo=,iv:sV3nMM0S/u2pKM44Yqg0n/3DZUW78j56FLVtg/c/4SY=,tag:P12gKiaV0WScD7EfqyRH4Q==,type:str]
Initial Root Token: ENC[AES256_GCM,data:9tghvtDnzkjO46JmGJJGNC3bylOLzJsgDOeLUg==,iv:HTDuwFQlAQKjjzUmiH3QmTzsiHJToUoJ5FDnVyyh31s=,tag:yaXUFAnE3TS3RULkbxihUw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:310830963532:key/mrk-9e8c23191f1741289211dadb4d0767e8
          created_at: "2023-01-14T14:13:43Z"
          enc: AQICAHg/l3PW9DQsmOmkmKzHr1yZLJ4ZNJ0/QSakfJT5vDDv+wHQoFhGvsAHICWApd+PZZEfAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbCQbEhxqe3clEmpUAgEQgDsOlun0ErCSRfLsvmxq7ypT340+31YoTL/Ad9KVJDIt3ThnKtjTkJdMowEYpnrhyOJzicM+7BGIZyfJSw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-22T22:55:22Z"
    mac: ENC[AES256_GCM,data:tBNWJlfRqo8k9s/W9PXoY5D6IBypvy+SvAZyckn6gwfosibtmVW+QN0FLhORI6vvI7etnO7mKozyQ9Y8TyYVzza3yMPZsaVeR4AvStYIGLRasA6VYdy6J4RRjie3kxg8ZaJxxKE0Kbc4aqyFmG9S8K9QKi+CRwUD1fq3IgpoFts=,iv:+Xa2j2/dbLZ3bdz692kE8TFaphgV+G6941cgIGrquhw=,tag:9LPFpXqgIsd+dRiB/NbJHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
