prometheus:
    additionalScrapeConfigs:
        basic_auth:
            username: ENC[AES256_GCM,data:02IqN6k=,iv:09wUiaqdqMGqQu+NyMtRVxp1uc+fdbjVkLKhg6FECJE=,tag:j3+TiDDSQvhXr9s4Owyt+A==,type:str]
            password: ENC[AES256_GCM,data:xAuRlDakfvey+MrCnXwqVs48z1M=,iv:L28uKd/36yzzvz3uvVJ9UzhDTyU5rlnB+U+X3dmE9V8=,tag:TQRpy7TMaO2j6sjlq6Nwcg==,type:str]
client_id: ENC[AES256_GCM,data:GqDCXCOcBC3hQwCM5x9D708w,iv:+nIzFxWrpdk/oribTI7x99cbfaxJxZFZYg4EK7e4s9g=,tag:CJXLsIGB1M6c5z2Uv37DkQ==,type:str]
client_secret: ENC[AES256_GCM,data:sZRQ83O9kr7FyYNSOo6G60QuKHMKSWPPkbGgWcm0qFQ=,iv:A0vF6bUjGIF7m6wRgGIhl2f0jKMJSXv8RCxMF9CbDh4=,tag:ikEIKimhWYXz+7GLlgPJ4A==,type:str]
opsgenie:
    apiKey: ENC[AES256_GCM,data:8w1rxob1CjDM8YH6FBDiKeEKYBPk17yITzP5nX7FSllMpHTT,iv:GnKb3EiMPDWvdDe9t14vkJF69JYim1Cz1GhFBmzul0k=,tag:Mmd/qxeizs2KWz4LTom3rg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:310830963532:key/mrk-9e8c23191f1741289211dadb4d0767e8
          created_at: "2022-06-17T17:20:44Z"
          enc: AQICAHg/l3PW9DQsmOmkmKzHr1yZLJ4ZNJ0/QSakfJT5vDDv+wEUrl553ne61PpRzrfb8ibmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXd+Jyyo86wg6wCCWAgEQgDtrG2VZ9/EBbF0bo0YG+mQrNL888jjWCvH2PgeKAgoOvwzdj6xIIkd9JXSH1WNrkJR3wTdXQkQUdg78Zw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-17T19:46:42Z"
    mac: ENC[AES256_GCM,data:74isZ4zlV/4Ng6xMu8z/otYlSUIStat+Wfi175jh91zUhBdpJqb28MnpEITDP6GLZ6wVRCp0CfwJhkghhps6H4Zqz/qepB0DbcRtPmZQVxkBJ9ui1XV2aa1zap/B6Iehr/xS9ox5YDwFl6a+0ggoCmrF7qFS3dKxiBLnidC99KQ=,iv:wQnSFFvwmqmtICHYl5O23+dopIP0oMkc23Gl9KpnG0A=,tag:6JMvHK3yz7OgkmK9tWMRHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
